image: jakzal/phpqa:php8.4

before_script:
    - composer install


cache:
    paths:
        - vendor/

stages:

    - CodingStandards



phpcs:
    stage: CodingStandards
    script:
        - phpcs -v --standard=PSR12 --ignore=./src/Kernel.php ./src
    allow_failure: false


